spring.application.name=clinic-api

spring.datasource.url=jdbc:h2:file:./data/clinicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=troqueEstaChaveSecretaPorUmaBemLongaEAleatoriaAntesDeIrParaProducao
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080
